### PR TITLE
Feature/live test for create branch in empty repo

### PR DESCRIPTION
**Pull request by martinda**
This builds on PR #147 by adding a live test that creates a branch in an empty repository.

### CODE REVIEW

**Comment by cdancy** [comment]
Pulling it in. Thanks @martinda !

**Comment by cdancy** [comment]
Might be backing out these changes as current live tests have loads of failures now and totally forgot that the generated empty repos also need to clean up after themselves.

**Comment by martinda** [comment]
All the tests pass for me (mock and integration). When the DEV project does not exist at the start of the tests, nothing is left in bitbucket after the tests are done. The test user is gone, and the DEV project and all its repos are gone too.

@cdancy can you share what goes wrong? Maybe I forgot to clean up something.

**Comment by cdancy** [comment]
@martinda try pulling from master and give things a go. I had about 9 failures but haven't had the time to look into things yet as I've been busy with something else.

**Comment by martinda** [comment]
I don't see any errors at my end with the latest master (be1f953e7).

I do see left over git repositories in `build/integ-projects`, but these do not cause errors. I can submit a PR that removes them when the tests are done.

Maybe try emptying the DEV project before you start?

Here is what I get:
```bash
cosmo:bitbucket-rest (master $%>) git remote -v show
origin	https://github.com/martinda/bitbucket-rest.git (fetch)
origin	https://github.com/martinda/bitbucket-rest.git (push)
upstream	https://github.com/cdancy/bitbucket-rest.git (fetch)
upstream	https://github.com/cdancy/bitbucket-rest.git (push)
cosmo:bitbucket-rest (master $%>) git pull upstream master
From https://github.com/cdancy/bitbucket-rest
 * branch            master     -> FETCH_HEAD
Already up-to-date.
cosmo:bitbucket-rest (master $%>) ./gradlew clean

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
cosmo:bitbucket-rest (master $%>) ./gradlew integTest -Ptest.bitbucket.endpoint=http://localhost:7990 -PtestBitbucketRestCredentials=martin:martin
...
BUILD SUCCESSFUL in 36s
5 actionable tasks: 5 executed
cosmo:bitbucket-rest (master $%>)
```

**Comment by cdancy** [comment]
Can't empty the DEV project on my end as that points to a real thing. But yeah the extra repos would have to be deleted as well. I wonder if there is a better way to do this in a more ad-hoc fashion so that we are not creating them unnecessarily.

**Comment by martinda** [comment]
If `DEV` is taken, you come up with a non-existent project of your choice:
```
./gradlew integTest -PtestBitbucketRestProject=DEV2
```

I am looking into deleting those git directories, but `gitDirectory.delete()` fails, there is probably a file handle still open or something like that. I'll see what I can find.

**Pull request merged**
