### PR TITLE
Bitbucket Server: Search API (/rest/search/{version}/search)

### PR DESCRIPTION
**Pull request by thlaegler**
Implementation of Feature `Search API`: #241

### CODE REVIEW

**Review by cdancy — APPROVED** [review]
@thlaegler I'm fine with this. Anything else you want to add or do here?

**Comment by thlaegler** [comment]
I'm fine with it. Would be good to test it against other Bitbucket versions. Maybe even Bitbucket Cloud.

**Comment by cdancy** [comment]
@thlaegler what did you test against? We have v7.4.0 here that I can run against.

Also ... would it make sense to allow for passing in a raw string to the "SearchRequest" object on top of the map and json versions we have now? I could see that being useful for users who want to quickly build something out with a string.

**Comment by thlaegler** [comment]
I tested with v7.3.1
Good idea with quick search. Actually, paging could also be implemented. But it looks like the paging works a bit different than the other paging-APIs so I didn't implemented it

**Comment by cdancy** [comment]
@thlaegler sorry for the delay. There were checkstyle issues when I ran locally and didn't have the time to address them until now. `2.7.1` is now released and should be good to go.

**Pull request merged**
