### PR TITLE
Factorize Links attributes in domain classes with LinksHolder interface

### PR DESCRIPTION
**Pull request by Gawen-pjr**
Same work as in PR #25, but for "Links" attributes this time.

### CODE REVIEW

**Comment by cdancy** [comment]
@Gawen-pjr can you add mock tests (simple assertion will suffice) for those features that have links to ensure they are not null, or are null, when expected?

**Comment by Gawen-pjr** [comment]
Mock test added

**Comment by Gawen-pjr** [comment]
I have a question regarding the potential next PR : 

What is the purpose of package `com.cdancy.bitbucket.rest.options`, and why is this package not a sub-package of `com.cdancy.bitbucket.rest.domain` (as it defines model-related classes) ?

If I were you, I'd put these classes in their corresponding domain package (for example `CreateProject` in `com.cdancy.bitbucket.rest.domain.project`). What do you think about this?

**Comment by cdancy** [comment]
@Gawen-pjr lets keep them where they are. I agree with your assessment but I'm following the [jclouds](https://github.com/jclouds/jclouds-labs) model so as to keep things inline with their standards as much as possible.

**Comment by cdancy** [comment]
Live tests pass as expected. Thanks for the PR @Gawen-pjr !!!

**Pull request merged**
