### PR TITLE
Adding project permissions #159

### PR DESCRIPTION
**Pull request by kmoco2am**
Adding project level permissions API (#159) which is very similar to repository level permissions (most of the code reused and tests added too).

### CODE REVIEW

**Comment by cdancy** [comment]
This looks pretty good I must say and thanks for the contribution. I'm away from a working Bitbucket instance at the moment but will have one in the morning to test things out. Other than that I have no complaints. So long as everything works as expected I'll merge tomorrow morning and kick a new release.

**Comment by cdancy** [comment]
Thanks @kmoco2am for the PR! Merging this now. Will kick a new release momentarily.

**Comment by cdancy** [comment]
@kmoco2am version `2.3.0` has been released.

**Comment by kmoco2am** [comment]
Many thanks. This is one of the fastest merge I have ever seen. New version works for me like a charm.

**Pull request merged**
