### PR TITLE
use correct data formats in InsightReportData value

### LINKED ISSUE #208: Code Insight API ReportData can have values of different types
### Expected Behavior
Adding ReportData of DataTypes other than TEXT should work

### Current Behavior
Only adding ReportData of DataType TEXT works, because other types need to be encoded as described here:
https://docs.atlassian.com/bitbucket-server/rest/6.9.0/bitbucket-code-insights-rest.html#idp9
But currently every type is encoded as a string.

### Context
I was trying to add a link to a report.

### Steps to Reproduce (for bugs)
```
val data = InsightReportData.create("Title", InsightReportData.DataType.LINK, "https://example.com/insightReportData");
val report = CreateInsightReport.create("", "https://example.com/buildUrl", null, CreateInsightReport.RESULT.PASS, "", "", List.of(data));
insightsApi.createReport("project", "repo", "commit", "key", report);
```

### Your Environment
Java 11
Jenkins CI

So I already fixed this, but then read that I should create an issue first.
Just tell me if I should open a PR.

### PR DESCRIPTION
**Pull request by succcubbus**
Adding Code Insight ReportData of DataTypes other than TEXT should now work

closes #208 

During live testing I got a few `*** Please tell me who you are.` messages, and I don't know how to fix these.
So the live tests could be broken.

### CODE REVIEW

**Comment by succcubbus** [comment]
The same integration tests are failing for me on master, so it's probably something about my local bitbucket instance.

**Comment by cdancy** [comment]
@succcubbus got it working here locally. Will merge this in, apply fix, and kick a new point release. Thanks for the PR!

**Comment by cdancy** [comment]
FWIW: had to massage the test to include less than or equal to 6 items in the `data` list as my bitbucket instance was complaining I could not send in a list with more than that. Not sure if that's a config someone can increase or a hard default.

**Comment by cdancy** [comment]
Version `2.6.2` released with this fix. Thanks again!

**Comment by succcubbus** [comment]
whoa that was fast
I expected to wait a bit for the next release
awesome

**Pull request merged**
