### PR TITLE
Adding WebHook API methods

### PR DESCRIPTION
**Pull request by Joni-Lover**
New WebHook API methods

#161

### CODE REVIEW

**Comment by cdancy** [comment]
This looks good. Normally I would ask that we break each endpoint down into its own PR but things look pretty clean at the moment. Before I can merge we will need mock and integration tests to confirm everything works as expected. If you need help with any of that feel free to ask.

**Comment by mronus** [comment]
@Joni-Lover Is there any progress on this subject? Just asking to be able to plan our roadmap for our product.

**Comment by Joni-Lover** [comment]
I guess in Mart-April I can spend time for write Tests for that.

**Comment by cdancy** [comment]
I can try to push this forward as I know folks have been asking about it. Might take me a few days to get to things but I think we can knock out a new release with these changes by next week.

**Comment by cdancy** [comment]
Closing this PR in favor of #176 which builds on top of this but adds live tests. I'll update here as well once the PR is merged and a new release is available which should be within the next hour or so.

**Comment by cdancy** [comment]
@Joni-Lover @mronus version `2.5.0` has been released with these changes.

**Comment by mronus** [comment]
Thanks a lot for your great effort guys!

**Pull request closed without merging**
