### PR TITLE
Adding labels api support

### PR DESCRIPTION
**Pull request by shinusuresh**
PR for #182 
Adding support to `/rest/api/1.0/labels` API endpoint in https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html#idp86

### CODE REVIEW

**Comment by cdancy** [comment]
@shinusuresh yeah this looks good. Anything more you want to do here?

**Comment by shinusuresh** [comment]
Hey @cdancy, thanks for reviewing. Nothing more in this PR.
There are a couple of other API's in label. Will do it as new issues.

**Comment by cdancy** [comment]
@shinusuresh did you want a new release for this work or did you want to wait until you've coded up the other methods?

**Comment by shinusuresh** [comment]
@cdancy No. Will have a release once the remaining methods are in.
Thanks for checking.

**Pull request merged**
