### PR TITLE
Removing unused variables and imports

### PR DESCRIPTION
**Pull request by tomasbjerre**

### CODE REVIEW

**Comment by cdancy** [comment]
@tomasbjerre just getting back to review these changes now. We've had an ant-to-gradle followed by svn-to-git migration these past few weeks here and its been a little busy working on the automation for it all: my apologies. Thanks for breaking this out into a separate PR.

**Comment by tomasbjerre** [comment]
Sounds fun :)

I actually ended up not using this lib. Its really nice but I got problems
because of all the dependencies it adds to the classpath. It gave me
problems when using it in a Jenkins plugin.

Den 8 aug. 2016 16:51 skrev "Christopher Dancy" <notifications@github.com>:

**Comment by cdancy** [comment]
@tomasbjerre really? What were the issues if you still have them? I do publish `fat` jar which should get around any dependency type of issues that may arise.

**Comment by cdancy** [comment]
@tomasbjerre also: if you're not going to continue on with the work I'm going to fork your branch and clean things up anyway. Now that we are live with gradle and git those backlog items I had, which you started coding for, are now needed by myself ;)

**Comment by tomasbjerre** [comment]
Problem was with ***guice-assistedinject*** I think Jenkins is using 4 och JClouds is using 3. I just tried it with the SNAPSHOT-version I build locally.

Ok, hope you find something you can use in my fork =)

**Pull request merged**
