### PR TITLE
Feature/expose modules for logging

### PR DESCRIPTION
**Pull request by richabindra**
This PR addresses Issue #156.  A module option is added to the builder, so logging can be added at the application level if needed.

### CODE REVIEW

**Comment by cdancy** [comment]
Code LGTM. Yeah not sure if you can just clone the wiki over or if it will come with the branch. @martinda do you remember how you did this?

**Comment by martinda** [comment]
The documentation is on a different upstream, in this case it would be `https://github.com/cdancy/bitbucket-rest.wiki.git` and it is not possible to use pull-requests, so for `jenkins-rest` I had to push directly to the `cdancy` user space. I had to push to master directly, and correct mistakes by pushing fixes.

**Comment by richabindra** [comment]
Ran the code in the examples as @martinda suggested.  The example was tested by setting the version of jenkins-rest to 2.2.1-SNAPSHOT locally, and is published with version set to 2.2.1.

**Comment by cdancy** [comment]
@richabindra thanks for the PR! I can kick an new patch release ASAP if you want one. Just let me know.

**Comment by richabindra** [comment]
@cdancy - yes, a new patch release would be great!  thank you :)

**Comment by cdancy** [comment]
@richabindra version `2.2.1` is now available.

**Comment by richabindra** [comment]
@cdancy - thank you.. appreciate the quick response :)

**Comment by cdancy** [comment]
@richabindra you're welcome and no problem.

**Comment by richabindra** [comment]
@cdancy - I tried pushing wiki page directly to your repository, but I am getting permission denied (obviously, but I just wanted to try). How do you want to go about moving wiki to your space?

**Comment by cdancy** [comment]
@richabindra try again. I just opened things up to allow anyone to edit.

**Comment by richabindra** [comment]
@cdancy - done. thank you.  I have added logging page to wiki. Please review and let me know if there is anything that needs to be fixed..

**Comment by cdancy** [comment]
@richabindra nope that looks great and thanks for adding it.

**Pull request merged**
