### PR TITLE
Moving comment on path to comments API

### PR DESCRIPTION
**Pull request by tomasbjerre**

### CODE REVIEW

**Comment by tomasbjerre** [comment]
What do you think @cdancy ? Does it not belong in the comments API?

**Comment by cdancy** [comment]
Agreed. Lets move it. Can you address the checkstyle violations and I'll merge?

**Comment by tomasbjerre** [comment]
Done.

Will you do a release soon? I want to use it in [a Jenkins plugin](https://github.com/jenkinsci/violation-comments-to-stash-plugin).

**Comment by cdancy** [comment]
I can knock one out within the next day or so. Wanted to get one more thing in before release.

That looks like a very useful plugin actually. I'm going to pass it around to folks here to see what they think. Thanks for tagging it!

**Comment by cdancy** [comment]
@tomasbjerre can a new release wait until early next week? Reviewing a couple PR's now that I'd like to get in. I'll knock a release out for you if you need one as I told you I would but if it can wait a few more days that would be great.

**Comment by tomasbjerre** [comment]
Yes it can wait :)

Den 9 mars 2017 15:33 skrev "Christopher Dancy" <notifications@github.com>:

**Comment by cdancy** [comment]
FYI: released v0.0.14.

**Pull request merged**
