### PR TITLE
Pr/173

### PR DESCRIPTION
**Pull request by cdancy**
Taking this PR in favor of https://github.com/cdancy/bitbucket-rest/pull/173

### CODE REVIEW

**Comment by cdancy** [comment]
@adam-tylr not sure if you hit similar issues but I had trouble running the `FileApiLiveTests` due to commits not being properly pushed. Not sure what the deal is there so I'll have to circle back around. Your code however look good and worked as expected.

**Comment by cdancy** [comment]
Version `2.4.2` has been released with these changes. Let me know how things go.

**Comment by adam-tylr** [comment]
@cdancy thanks for creating a release. I didn't have any trouble with the live tests. I don't know what happened there.

**Comment by cdancy** [comment]
Maybe it was environmental on my part. IDK. The code was good though which is all that matters. Thanks for the PR.

**Pull request merged**
